/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inox;

import java.awt.Toolkit;
import java.sql.Connection;
import static java.sql.JDBCType.NULL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Varun
 */
public class bookon1 extends javax.swing.JFrame {

    
    int[] seatbook=new int[41]; 
    int i=1;
    int max=0;
    int price=0;
    String str="";
    public bookon1() {
        initComponents();
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("fav.png")));
        panel1.setVisible(false);
        book.setEnabled(false);
        Connection conn= DBConnection.connect();
          if(conn != null)
        {
            String sql;
                sql = "select * from movie where id=1";
                try{
                    Statement stat = conn.createStatement();
                    ResultSet rs=null;
                    rs=stat.executeQuery(sql);
                        if(rs.next())
                        {
                            filmname.setText(rs.getString("name"));
                            price=rs.getInt("price");
                        }
                    }
                catch(SQLException ex)
                {
                
                }
        }
           else
            {
                JOptionPane.showMessageDialog(null, "Not connected");
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b29 = new javax.swing.JButton();
        b30 = new javax.swing.JButton();
        b36 = new javax.swing.JButton();
        b37 = new javax.swing.JButton();
        b38 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        b27 = new javax.swing.JButton();
        b28 = new javax.swing.JButton();
        b39 = new javax.swing.JButton();
        b40 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        b34 = new javax.swing.JButton();
        b35 = new javax.swing.JButton();
        filmname = new javax.swing.JLabel();
        seats = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        arrayseats = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        timing = new javax.swing.JComboBox<>();
        check = new javax.swing.JButton();
        book = new javax.swing.JButton();
        bill = new javax.swing.JButton();
        totalrs = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        b9.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b9.setText("9");
        b9.setMaximumSize(new java.awt.Dimension(60, 60));
        b9.setMinimumSize(new java.awt.Dimension(60, 60));
        b9.setPreferredSize(new java.awt.Dimension(60, 60));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b10.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b10.setText("10");
        b10.setMaximumSize(new java.awt.Dimension(60, 60));
        b10.setMinimumSize(new java.awt.Dimension(60, 60));
        b10.setPreferredSize(new java.awt.Dimension(60, 60));
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b1.setText("1");
        b1.setMaximumSize(new java.awt.Dimension(60, 60));
        b1.setMinimumSize(new java.awt.Dimension(60, 60));
        b1.setPreferredSize(new java.awt.Dimension(60, 60));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b2.setText("2");
        b2.setMaximumSize(new java.awt.Dimension(60, 60));
        b2.setMinimumSize(new java.awt.Dimension(60, 60));
        b2.setPreferredSize(new java.awt.Dimension(60, 60));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b3.setText("3");
        b3.setMaximumSize(new java.awt.Dimension(60, 60));
        b3.setMinimumSize(new java.awt.Dimension(60, 60));
        b3.setPreferredSize(new java.awt.Dimension(60, 60));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b4.setText("4");
        b4.setMaximumSize(new java.awt.Dimension(60, 60));
        b4.setMinimumSize(new java.awt.Dimension(60, 60));
        b4.setPreferredSize(new java.awt.Dimension(60, 60));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b5.setText("5");
        b5.setMaximumSize(new java.awt.Dimension(60, 60));
        b5.setMinimumSize(new java.awt.Dimension(60, 60));
        b5.setPreferredSize(new java.awt.Dimension(60, 60));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b6.setText("6");
        b6.setMaximumSize(new java.awt.Dimension(60, 60));
        b6.setMinimumSize(new java.awt.Dimension(60, 60));
        b6.setPreferredSize(new java.awt.Dimension(60, 60));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b7.setText("7");
        b7.setMaximumSize(new java.awt.Dimension(60, 60));
        b7.setMinimumSize(new java.awt.Dimension(60, 60));
        b7.setPreferredSize(new java.awt.Dimension(60, 60));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b8.setText("8");
        b8.setMaximumSize(new java.awt.Dimension(60, 60));
        b8.setMinimumSize(new java.awt.Dimension(60, 60));
        b8.setPreferredSize(new java.awt.Dimension(60, 60));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b19.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b19.setText("19");
        b19.setMaximumSize(new java.awt.Dimension(60, 60));
        b19.setMinimumSize(new java.awt.Dimension(60, 60));
        b19.setPreferredSize(new java.awt.Dimension(60, 60));
        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b20.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b20.setText("20");
        b20.setMaximumSize(new java.awt.Dimension(60, 60));
        b20.setMinimumSize(new java.awt.Dimension(60, 60));
        b20.setPreferredSize(new java.awt.Dimension(60, 60));
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b11.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b11.setText("11");
        b11.setMaximumSize(new java.awt.Dimension(60, 60));
        b11.setMinimumSize(new java.awt.Dimension(60, 60));
        b11.setPreferredSize(new java.awt.Dimension(60, 60));
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b12.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b12.setText("12");
        b12.setMaximumSize(new java.awt.Dimension(60, 60));
        b12.setMinimumSize(new java.awt.Dimension(60, 60));
        b12.setPreferredSize(new java.awt.Dimension(60, 60));
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b13.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b13.setText("13");
        b13.setMaximumSize(new java.awt.Dimension(60, 60));
        b13.setMinimumSize(new java.awt.Dimension(60, 60));
        b13.setPreferredSize(new java.awt.Dimension(60, 60));
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b14.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b14.setText("14");
        b14.setMaximumSize(new java.awt.Dimension(60, 60));
        b14.setMinimumSize(new java.awt.Dimension(60, 60));
        b14.setPreferredSize(new java.awt.Dimension(60, 60));
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b15.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b15.setText("15");
        b15.setMaximumSize(new java.awt.Dimension(60, 60));
        b15.setMinimumSize(new java.awt.Dimension(60, 60));
        b15.setPreferredSize(new java.awt.Dimension(60, 60));
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b16.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b16.setText("16");
        b16.setMaximumSize(new java.awt.Dimension(60, 60));
        b16.setMinimumSize(new java.awt.Dimension(60, 60));
        b16.setPreferredSize(new java.awt.Dimension(60, 60));
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b17.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b17.setText("17");
        b17.setMaximumSize(new java.awt.Dimension(60, 60));
        b17.setMinimumSize(new java.awt.Dimension(60, 60));
        b17.setPreferredSize(new java.awt.Dimension(60, 60));
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b18.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b18.setText("18");
        b18.setMaximumSize(new java.awt.Dimension(60, 60));
        b18.setMinimumSize(new java.awt.Dimension(60, 60));
        b18.setPreferredSize(new java.awt.Dimension(60, 60));
        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b29.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b29.setText("29");
        b29.setMaximumSize(new java.awt.Dimension(60, 60));
        b29.setMinimumSize(new java.awt.Dimension(60, 60));
        b29.setPreferredSize(new java.awt.Dimension(60, 60));
        b29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b30.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b30.setText("30");
        b30.setMaximumSize(new java.awt.Dimension(60, 60));
        b30.setMinimumSize(new java.awt.Dimension(60, 60));
        b30.setPreferredSize(new java.awt.Dimension(60, 60));
        b30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b36.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b36.setText("36");
        b36.setMaximumSize(new java.awt.Dimension(60, 60));
        b36.setMinimumSize(new java.awt.Dimension(60, 60));
        b36.setPreferredSize(new java.awt.Dimension(60, 60));
        b36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b37.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b37.setText("37");
        b37.setMaximumSize(new java.awt.Dimension(60, 60));
        b37.setMinimumSize(new java.awt.Dimension(60, 60));
        b37.setPreferredSize(new java.awt.Dimension(60, 60));
        b37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b38.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b38.setText("38");
        b38.setMaximumSize(new java.awt.Dimension(60, 60));
        b38.setMinimumSize(new java.awt.Dimension(60, 60));
        b38.setPreferredSize(new java.awt.Dimension(60, 60));
        b38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b21.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b21.setText("21");
        b21.setMaximumSize(new java.awt.Dimension(60, 60));
        b21.setMinimumSize(new java.awt.Dimension(60, 60));
        b21.setPreferredSize(new java.awt.Dimension(60, 60));
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b22.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b22.setText("22");
        b22.setMaximumSize(new java.awt.Dimension(60, 60));
        b22.setMinimumSize(new java.awt.Dimension(60, 60));
        b22.setPreferredSize(new java.awt.Dimension(60, 60));
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b23.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b23.setText("23");
        b23.setMaximumSize(new java.awt.Dimension(60, 60));
        b23.setMinimumSize(new java.awt.Dimension(60, 60));
        b23.setPreferredSize(new java.awt.Dimension(60, 60));
        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b24.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b24.setText("24");
        b24.setMaximumSize(new java.awt.Dimension(60, 60));
        b24.setMinimumSize(new java.awt.Dimension(60, 60));
        b24.setPreferredSize(new java.awt.Dimension(60, 60));
        b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b25.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b25.setText("25");
        b25.setMaximumSize(new java.awt.Dimension(60, 60));
        b25.setMinimumSize(new java.awt.Dimension(60, 60));
        b25.setPreferredSize(new java.awt.Dimension(60, 60));
        b25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b26.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b26.setText("26");
        b26.setMaximumSize(new java.awt.Dimension(60, 60));
        b26.setMinimumSize(new java.awt.Dimension(60, 60));
        b26.setPreferredSize(new java.awt.Dimension(60, 60));
        b26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b27.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b27.setText("27");
        b27.setMaximumSize(new java.awt.Dimension(60, 60));
        b27.setMinimumSize(new java.awt.Dimension(60, 60));
        b27.setPreferredSize(new java.awt.Dimension(60, 60));
        b27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b28.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b28.setText("28");
        b28.setMaximumSize(new java.awt.Dimension(60, 60));
        b28.setMinimumSize(new java.awt.Dimension(60, 60));
        b28.setPreferredSize(new java.awt.Dimension(60, 60));
        b28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b39.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b39.setText("39");
        b39.setMaximumSize(new java.awt.Dimension(60, 60));
        b39.setMinimumSize(new java.awt.Dimension(60, 60));
        b39.setPreferredSize(new java.awt.Dimension(60, 60));
        b39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b40.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b40.setText("40");
        b40.setMaximumSize(new java.awt.Dimension(60, 60));
        b40.setMinimumSize(new java.awt.Dimension(60, 60));
        b40.setPreferredSize(new java.awt.Dimension(60, 60));
        b40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b31.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b31.setText("31");
        b31.setMaximumSize(new java.awt.Dimension(60, 60));
        b31.setMinimumSize(new java.awt.Dimension(60, 60));
        b31.setPreferredSize(new java.awt.Dimension(60, 60));
        b31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b32.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b32.setText("32");
        b32.setMaximumSize(new java.awt.Dimension(60, 60));
        b32.setMinimumSize(new java.awt.Dimension(60, 60));
        b32.setPreferredSize(new java.awt.Dimension(60, 60));
        b32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b33.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b33.setText("33");
        b33.setMaximumSize(new java.awt.Dimension(60, 60));
        b33.setMinimumSize(new java.awt.Dimension(60, 60));
        b33.setPreferredSize(new java.awt.Dimension(60, 60));
        b33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b34.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b34.setText("34");
        b34.setMaximumSize(new java.awt.Dimension(60, 60));
        b34.setMinimumSize(new java.awt.Dimension(60, 60));
        b34.setPreferredSize(new java.awt.Dimension(60, 60));
        b34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        b35.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        b35.setText("35");
        b35.setMaximumSize(new java.awt.Dimension(60, 60));
        b35.setMinimumSize(new java.awt.Dimension(60, 60));
        b35.setPreferredSize(new java.awt.Dimension(60, 60));
        b35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookon1.this.actionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(77, 77, 77)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b38, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(b28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b18, javax.swing.GroupLayout.PREFERRED_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(b19, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        filmname.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N

        seats.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        seats.setText("Selected Seats: ");

        reset.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        arrayseats.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N

        title1.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        title1.setText("Auditorium 01 -");

        time.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        time.setText("Shoow Time:");

        timing.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        timing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12pm to 3pm", "3pm to 6pm", "9pm to 12am" }));

        check.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        check.setText("Check");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        book.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        book.setText("Book Now");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });

        bill.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        bill.setText("Generate Bill");
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });

        totalrs.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel1.setText("Total Ammount:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(timing, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filmname, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(seats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(totalrs, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(280, 280, 280)
                                .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(arrayseats, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filmname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time)
                    .addComponent(timing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(seats)
                    .addComponent(arrayseats, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book)
                    .addComponent(bill)
                    .addComponent(reset))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed
        // TODO add your handling code here:
        JButton jb=(JButton) evt.getSource();
        seatbook[i]=Integer.parseInt(jb.getText());
        i++;
        jb.setEnabled(false);
        str=str+jb.getText()+",";
        arrayseats.setText(str);
    }//GEN-LAST:event_actionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        new bookon1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resetActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
        i=1;
        Arrays.fill(seatbook, 0);
        str="";
        arrayseats.setText(str);
        totalrs.setText("");
        panel1.setVisible(true);
        bill.setEnabled(true);
        b1.setEnabled(true);
        b2.setEnabled(true);
        b3.setEnabled(true);
        b4.setEnabled(true);
        b5.setEnabled(true);
        b6.setEnabled(true);
        b7.setEnabled(true);
        b8.setEnabled(true);
        b9.setEnabled(true);
        b10.setEnabled(true);
        b11.setEnabled(true);
        b12.setEnabled(true);
        b13.setEnabled(true);
        b14.setEnabled(true);
        b15.setEnabled(true);
        b16.setEnabled(true);
        b17.setEnabled(true);
        b18.setEnabled(true);
        b19.setEnabled(true);
        b20.setEnabled(true);
        b21.setEnabled(true);
        b22.setEnabled(true);
        b23.setEnabled(true);
        b24.setEnabled(true);
        b25.setEnabled(true);
        b26.setEnabled(true);
        b27.setEnabled(true);
        b28.setEnabled(true);
        b29.setEnabled(true);
        b30.setEnabled(true);
        b31.setEnabled(true);
        b32.setEnabled(true);
        b33.setEnabled(true);
        b34.setEnabled(true);
        b35.setEnabled(true);
        b36.setEnabled(true);
        b37.setEnabled(true);
        b38.setEnabled(true);
        b39.setEnabled(true);
        b40.setEnabled(true);
        
         String timesh= String.valueOf(timing.getSelectedItem());
        Connection conn= DBConnection.connect();
        if(conn != null)
        {
            String sql;
                sql = "select * from hall1 where status='booked' and showtime=?";
                try{
                    PreparedStatement stat;
                    stat= conn.prepareStatement(sql);
                    stat.setString(1,timesh);
                    ResultSet rs= stat.executeQuery();
                    while(rs.next())
                    {
                        int x=rs.getInt("seat");
                        if(x==1)
                        b1.setEnabled(false);
                        else if(x==2)
                        b2.setEnabled(false);
                        else if(x==3)
                        b3.setEnabled(false);
                        else if(x==4)
                        b4.setEnabled(false);
                        else if(x==5)
                        b5.setEnabled(false);
                        else if(x==6)
                        b6.setEnabled(false);
                        else if(x==7)
                        b7.setEnabled(false);
                        else if(x==8)
                        b8.setEnabled(false);
                        else if(x==9)
                        b9.setEnabled(false);
                        else if(x==10)
                        b10.setEnabled(false);
                        else if(x==11)
                        b11.setEnabled(false);
                        else if(x==12)
                        b12.setEnabled(false);
                        else if(x==13)
                        b13.setEnabled(false);
                        else if(x==14)
                        b14.setEnabled(false);
                        else if(x==15)
                        b15.setEnabled(false);
                        else if(x==16)
                        b16.setEnabled(false);
                        else if(x==17)
                        b17.setEnabled(false);
                        else if(x==18)
                        b18.setEnabled(false);
                        else if(x==19)
                        b19.setEnabled(false);
                        else if(x==20)
                        b20.setEnabled(false);
                        else if(x==21)
                        b21.setEnabled(false);
                        else if(x==22)
                        b22.setEnabled(false);
                        else if(x==23)
                        b23.setEnabled(false);
                        else if(x==24)
                        b24.setEnabled(false);
                        else if(x==25)
                        b25.setEnabled(false);
                        else if(x==26)
                        b26.setEnabled(false);
                        else if(x==27)
                        b27.setEnabled(false);
                        else if(x==28)
                        b28.setEnabled(false);
                        else if(x==29)
                        b29.setEnabled(false);
                        else if(x==30)
                        b30.setEnabled(false);
                        else if(x==31)
                        b31.setEnabled(false);
                        else if(x==32)
                        b32.setEnabled(false);
                        else if(x==33)
                        b33.setEnabled(false);
                        else if(x==34)
                        b34.setEnabled(false);
                        else if(x==35)
                        b35.setEnabled(false);
                        else if(x==36)
                        b36.setEnabled(false);
                        else if(x==37)
                        b37.setEnabled(false);
                        else if(x==38)
                        b38.setEnabled(false);
                        else if(x==39)
                        b39.setEnabled(false);
                        else if(x==40)
                        b40.setEnabled(false);
                    }
                }
                catch(SQLException ex)
                {
                
                }
        }
         else
            {
               
            }
    }//GEN-LAST:event_checkActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        // TODO add your handling code here:
         Connection conn= DBConnection.connect();
         String timesh= String.valueOf(timing.getSelectedItem());
         int rowupdate=0;
         if(conn != null)
        {
            String sql;
                sql = "insert into hall1(seat,showtime,status) values(?,?,?)";
                try{
                    i=1;
                    while(i<=max)
                    {
                        PreparedStatement stat;
                        stat= conn.prepareStatement(sql);
                        stat.setInt(1,seatbook[i]);
                        stat.setString(2,timesh);
                        stat.setString(3,"booked");
                        rowupdate= stat.executeUpdate();
                        i++;
                    }
                    if (rowupdate>0) {
                        JOptionPane.showMessageDialog(null, "Seats booked");
                        this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Seats not booked");
                    }
                }
                catch(SQLException ex)
                {
                
                }
        }
         else
            {
                JOptionPane.showMessageDialog(null, "Not connected");
            }
    }//GEN-LAST:event_bookActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        // TODO add your handling code here:
        int k=1;
        max=0;
        while(seatbook[k]!=0)
        {
            max++;
            k++;
        }
        int total;
        total=max*price;
        totalrs.setText("Rs."+String.valueOf(total)+"/-");
        bill.setEnabled(false);
        book.setEnabled(true);
    }//GEN-LAST:event_billActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookon1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookon1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookon1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookon1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookon1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrayseats;
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b26;
    private javax.swing.JButton b27;
    private javax.swing.JButton b28;
    private javax.swing.JButton b29;
    private javax.swing.JButton b3;
    private javax.swing.JButton b30;
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b34;
    private javax.swing.JButton b35;
    private javax.swing.JButton b36;
    private javax.swing.JButton b37;
    private javax.swing.JButton b38;
    private javax.swing.JButton b39;
    private javax.swing.JButton b4;
    private javax.swing.JButton b40;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bill;
    private javax.swing.JButton book;
    private javax.swing.JButton check;
    private javax.swing.JLabel filmname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel1;
    private javax.swing.JButton reset;
    private javax.swing.JLabel seats;
    private javax.swing.JLabel time;
    private javax.swing.JComboBox<String> timing;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel totalrs;
    // End of variables declaration//GEN-END:variables
}
