/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inox;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Varun
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
       
        URL logourl=getClass().getResource("logo.png");
        Icon logoicon=new ImageIcon(logourl);
        back.setIcon(logoicon); 
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("fav.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        back = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        book = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        rembook = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        films = new javax.swing.JMenu();
        reports = new javax.swing.JMenu();
        movies = new javax.swing.JMenuItem();
        audi1 = new javax.swing.JMenuItem();
        audi2 = new javax.swing.JMenuItem();
        audi3 = new javax.swing.JMenuItem();
        malak = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        me = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jMenuBar1.add(home);

        book.setText("Booking");
        book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookMouseClicked(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem3.setText("Book Now");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        book.add(jMenuItem3);

        rembook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_MASK));
        rembook.setText("Cancel Booking");
        rembook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rembookActionPerformed(evt);
            }
        });
        book.add(rembook);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem4.setText("Clear Booking");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        book.add(jMenuItem4);

        jMenuBar1.add(book);

        films.setText("Movies");
        films.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filmsMouseClicked(evt);
            }
        });
        jMenuBar1.add(films);

        reports.setText("Booking Report");

        movies.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        movies.setText("Current Movies");
        movies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviesActionPerformed(evt);
            }
        });
        reports.add(movies);

        audi1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        audi1.setText("Auditorium No.1");
        audi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audi1ActionPerformed(evt);
            }
        });
        reports.add(audi1);

        audi2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        audi2.setText("Auditorium No.2");
        audi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audi2ActionPerformed(evt);
            }
        });
        reports.add(audi2);

        audi3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        audi3.setText("Auditorium No.3");
        audi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audi3ActionPerformed(evt);
            }
        });
        reports.add(audi3);

        jMenuBar1.add(reports);

        malak.setText("Admin");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setText("Log out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        malak.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setText("Change Password");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        malak.add(jMenuItem2);

        jMenuBar1.add(malak);

        me.setText("About");
        me.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meMouseClicked(evt);
            }
        });
        jMenuBar1.add(me);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new changepass().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        new menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void filmsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filmsMouseClicked
        // TODO add your handling code here:
         new addmovie().setVisible(true);
    }//GEN-LAST:event_filmsMouseClicked

    private void meMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meMouseClicked
        // TODO add your handling code here:
        new about().setVisible(true);
    }//GEN-LAST:event_meMouseClicked

    private void bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_bookMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new selectmovie().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void rembookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rembookActionPerformed
        // TODO add your handling code here:
        new rembooking().setVisible(true);
    }//GEN-LAST:event_rembookActionPerformed

    private void audi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audi2ActionPerformed
        // TODO add your handling code here:
        Connection conn= DBConnection.connect();
        if (conn!=null) {
           try
           {
                InputStream stream=this.getClass().getResourceAsStream("hall2.jrxml");
                JasperDesign jd=JRXmlLoader.load(stream);
                String sql="select * from hall2";
                PreparedStatement stat;
                stat = conn.prepareStatement(sql);
                ResultSet rs=stat.executeQuery();
                
                if (rs.next()) 
                {
                    JRDesignQuery newQuery=new JRDesignQuery();
                    newQuery.setText(sql);
                    jd.setQuery(newQuery);
                    JasperReport jr=JasperCompileManager.compileReport(jd);
                    JasperPrint jp=JasperFillManager.fillReport(jr,null,conn);
                    JasperViewer.viewReport(jp, false);   
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "not found");
                }
           }
           catch(Exception ex)
           {
             ex.printStackTrace();
           }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_audi2ActionPerformed

    private void audi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audi3ActionPerformed
        // TODO add your handling code here:
        Connection conn= DBConnection.connect();
        if (conn!=null) {
           try
           {
                InputStream stream=this.getClass().getResourceAsStream("hall3.jrxml");
                JasperDesign jd=JRXmlLoader.load(stream);
                String sql="select * from hall3";
                PreparedStatement stat;
                stat = conn.prepareStatement(sql);
                ResultSet rs=stat.executeQuery();
                
                if (rs.next()) 
                {
                    JRDesignQuery newQuery=new JRDesignQuery();
                    newQuery.setText(sql);
                    jd.setQuery(newQuery);
                    JasperReport jr=JasperCompileManager.compileReport(jd);
                    JasperPrint jp=JasperFillManager.fillReport(jr,null,conn);
                    JasperViewer.viewReport(jp, false);   
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "not found");
                }
           }
           catch(Exception ex)
           {
             ex.printStackTrace();
           }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_audi3ActionPerformed

    private void moviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moviesActionPerformed
        // TODO add your handling code here:
           Connection conn= DBConnection.connect();
        if (conn!=null) {
           try
           {
                InputStream stream=this.getClass().getResourceAsStream("movies.jrxml");
                JasperDesign jd=JRXmlLoader.load(stream);
                String sql="select * from movie";
                PreparedStatement stat;
                stat = conn.prepareStatement(sql);
                ResultSet rs=stat.executeQuery();
                
                if (rs.next()) 
                {
                    JRDesignQuery newQuery=new JRDesignQuery();
                    newQuery.setText(sql);
                    jd.setQuery(newQuery);
                    JasperReport jr=JasperCompileManager.compileReport(jd);
                    JasperPrint jp=JasperFillManager.fillReport(jr,null,conn);
                    JasperViewer.viewReport(jp, false);   
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "not found");
                }
           }
           catch(Exception ex)
           {
             ex.printStackTrace();
           }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error");
        }       
    }//GEN-LAST:event_moviesActionPerformed

    private void audi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audi1ActionPerformed
        // TODO add your handling code here:
        Connection conn= DBConnection.connect();
        if (conn!=null) {
           try
           {
                InputStream stream=this.getClass().getResourceAsStream("hall1.jrxml");
                JasperDesign jd=JRXmlLoader.load(stream);
                String sql="select * from hall1";
                PreparedStatement stat;
                stat = conn.prepareStatement(sql);
                ResultSet rs=stat.executeQuery();
                
                if (rs.next()) 
                {
                    JRDesignQuery newQuery=new JRDesignQuery();
                    newQuery.setText(sql);
                    jd.setQuery(newQuery);
                    JasperReport jr=JasperCompileManager.compileReport(jd);
                    JasperPrint jp=JasperFillManager.fillReport(jr,null,conn);
                    JasperViewer.viewReport(jp, false);   
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "not found");
                }
           }
           catch(Exception ex)
           {
               JOptionPane.showMessageDialog(null, ex);
             ex.printStackTrace();
           }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_audi1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         new clearbook().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem audi1;
    private javax.swing.JMenuItem audi2;
    private javax.swing.JMenuItem audi3;
    private javax.swing.JLabel back;
    private javax.swing.JMenu book;
    private javax.swing.JMenu films;
    private javax.swing.JMenu home;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu malak;
    private javax.swing.JMenu me;
    private javax.swing.JMenuItem movies;
    private javax.swing.JMenuItem rembook;
    private javax.swing.JMenu reports;
    // End of variables declaration//GEN-END:variables
}
